stages:
    - test

lint_and_test:
    stage: test
    tags:
        - test
    image: python:3.12-slim
    variables:
        JWT_DIR: "jwt_keys"
    before_script:
        - mkdir $JWT_DIR
        - echo "$JWT_PRIVATE" > $JWT_DIR/jwt-private.pem
        - echo "$JWT_PUBLIC" > $JWT_DIR/jwt-public.pem
    script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - black --check . 
        - mypy .
        - pytest tests/unit/ -v
