stages:
    - test
    - build
lint_and_test:
    stage: test
    tags:
        - test
    image: python:3.12-slim
    variables:
        JWT_DIR: "jwt_keys"
    before_script:
        - mkdir $JWT_DIR
        - echo "$JWT_PRIVATE" > $JWT_DIR/jwt-private.pem
        - echo "$JWT_PUBLIC" > $JWT_DIR/jwt-public.pem
    script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - black --check . 
        - mypy .
        - pytest tests/unit/ -v
build_and_push:
    stage: build
    tags:
        - build
    image: docker:20.10
    variables:
        DOCKER_HOST: unix:///var/run/docker.sock
        DOCKER_IMAGE: registry.gitlab.com/thetrueryan-group/event_trees
    script:
        - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA


