stages:
    - test

lint_and_test:
    stage: test
    tags:
        - test
    image: python:3.12-slim
    script:
        - pip install -r requirements.txt
        - black --check . 
        - mypy .
        - pytest tests/unit/ -v
