"""added name to events

Revision ID: 042cfb205e6c
Revises: 4a2f43ef5b8c
Create Date: 2025-08-24 22:24:47.090579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "042cfb205e6c"
down_revision: Union[str, Sequence[str], None] = "4a2f43ef5b8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "name")
    # ### end Alembic commands ###
