"""delete fk in parent_id

Revision ID: 2921a24441cc
Revises: 042cfb205e6c
Create Date: 2025-08-30 12:37:51.427797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2921a24441cc"
down_revision: Union[str, Sequence[str], None] = "042cfb205e6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "parent_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(op.f("events_parent_id_fkey"), "events", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("events_parent_id_fkey"), "events", "events", ["parent_id"], ["id"]
    )
    op.alter_column("events", "parent_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
