"""change parent_id to nullable=True

Revision ID: a8dc69a592dd
Revises: 2921a24441cc
Create Date: 2025-08-30 15:33:26.103676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8dc69a592dd"
down_revision: Union[str, Sequence[str], None] = "2921a24441cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "parent_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "parent_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
